import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import backgroundImage from "../../public/OIP.jpg";
import Header from "@resort-site/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundImage: `url(${backgroundImage.src})`,
          backgroundPosition: "center",
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat",
          width: "99vw",
          height: "100vh",
        }}
        className={`${inter.className} lg:pl-20`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
